version: "3.8"

services:
  api:
    build:
      context: ./api
    container_name: api-service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: frontend-service
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:5000
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
